apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/kubevirt-hyperconverged.openshift-cnv: ''
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  channel: candidate
  installPlanApproval: Manual
  name: kubevirt-hyperconverged
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: kubevirt-hyperconverged-operator.v4.20.3
{{- if .Values.kubevirt.config }}
{{ .Values.kubevirt.config | indent 2 }}
  config:
    env:
    - name: KVM_EMULATION
      value: "true"
{{- end }}
