apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    kubernetes.io/metadata.name: dynamic-schedule-stress-test
  name: dynamic-schedule-stress-test
