apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-test
  namespace: dynamic-schedule-stress-test
  labels:
    app: stress-test
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: 0
  selector:
    matchLabels:
      app: stress-test
  template:
    metadata:
      labels:
        app: stress-test
    spec:
      containers:
      - name: stress
        image: quay.io/rh_ee_mmayeras/stress:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: stress-config
        resources:
          requests:
            cpu: "2"
            memory: "1Gi"
      restartPolicy: Always



