---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-master-taint-job
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-master-taint-job
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: node-master-taint-job
  namespace: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: node-master-taint-job
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountname: node-master-taint-job
      containers:
      - name: node-master-taint-patch
        image: image-registry.openshift-image-registry.svc:5000/openshift/cli
        command:
        - /bin/sh
        - -c
        - |
          echo "######################"
          echo "# taint the master node"
          echo "######################"
          oc adm taint node -l node-role.kubernetes.io/master key=virtualization:NoSchedule
