---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-self-node-remediation-og
  namespace: openshift-workload-availability
spec:
  upgradeStrategy: Default
  targetNamespaces:
    - openshift-workload-availability
