---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: hot-plug-vm1
  namespace: hot-plug
spec:
  dataVolumeTemplates:
    - metadata:
        name: hot-plug-vm1-volume
      spec:
        sourceRef:
          kind: DataSource
          name: rhel10
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  instancetype:
    name: u1.small
  preference:
    name: rhel.10
  runStrategy: Manual
  template:
    metadata:
      labels:
        network.kubevirt.io/headlessService: headless
    spec:
      domain:
        cpu:
          model: EPYC
        devices:
          autoattachPodInterface: false
          disks:
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              name: default
      networks:
        - name: default
          pod: {}
      subdomain: headless
      volumes:
        - dataVolume:
            name: hot-plug-vm1-volume
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              chpasswd:
                expire: false
              password: redhat
              user: rhel
              bootcmd:
                - nmcli connection add type ethernet ifname enp2s0 con-name enp2s0 ipv4.method manual ipv4.address 192.168.20.11/24
                - nmcli connection add type ethernet ifname enp3s0 con-name enp3s0 ipv4.method manual ipv4.address 192.168.20.12/24
                - systemctl disable kdump
                - grubby --update-kernel=ALL --args="crashkernel"
          name: cloudinitdisk
