---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-migration-og
  namespace: openshift-migration
spec:
  upgradeStrategy: Default
  targetNamespaces:
    - openshift-migration
